name: "Padel Booking"
version: "2.1.9"
slug: "padel_booking"
description: "Automatisch padelbanen boeken op meetandplay.nl en Playtomic"
arch:
  - aarch64
  - amd64
init: false
hassio_api: true
homeassistant_api: true
map:
  - config:rw
options:
  knltb_email: ""
  knltb_password: ""
  playtomic_email: ""
  playtomic_password: ""
  ha_notify_device_id: ""
  location_city: "Boskoop"
  location_radius_km: 20
  location_latitude: 52.0738
  location_longitude: 4.6567
  booking_day: "thursday"
  booking_time_start: "19:30"
  booking_time_end: "21:00"
  duration_minutes: "90"
  court_type: "indoor"
  game_type: "double"
  weeks_ahead: 4
  meetandplay_enabled: true
  playtomic_enabled: false

schema:
  knltb_email: email
  knltb_password: password
  playtomic_email: str
  playtomic_password: str
  ha_notify_device_id: str?
  location_city: str
  location_radius_km: int
  location_latitude: float?
  location_longitude: float?
  booking_day: list(monday|tuesday|wednesday|thursday|friday|saturday|sunday)
  booking_time_start: match([0-2][0-9]:[0-5][0-9])
  booking_time_end: match([0-2][0-9]:[0-5][0-9])
  duration_minutes: list(60|90)
  court_type: list(indoor|outdoor)
  game_type: list(double|single)
  weeks_ahead: int
  meetandplay_enabled: bool
  playtomic_enabled: bool
